MS_TO_NS = 1e6
NS_TO_MS = 1e-6

RECORD_INTERVAL_IN_MS = 25
SAVE_INTERVAL_IN_S = 5

UPLOAD_INTERVALS_IN_S = 5

BASE_URL = "http://localhost:3000"
AUTH_URL = f"{BASE_URL}/auth"
SEND_URL = f"{BASE_URL}/send"
